apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-service
  namespace: golang-service
  labels:
    app: golang-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-service
  template:
    metadata:
      labels:
        app: golang-service
    spec:
      containers:
      - name: golang-service
        image: golang-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: golang-service-config
        - secretRef:
            name: golang-service-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL